# 기본 이미지 설정
FROM node:18-alpine

# yarn 설치
RUN npm install -g yarn --force

# 작업 디렉토리 설정
WORKDIR /src

# package.json과 yarn.lock 파일 복사
COPY package.json yarn.lock ./

# 의존성 설치
RUN yarn

# 애플리케이션 소스 코드 복사 (node_modules 제외)
COPY . .

EXPOSE 5173

# 애플리케이션 실행 명령
CMD ["yarn", "dev"]